### ISSUE TITLE
SampleNaitive not loading

### ISSUE THREAD

**Issue by mrbrennonwilliams** [Microsoft/WindowsCompositionSamples#277]
Hi all,

I've tried opening up the Sample Gallery sln and the 4th project SamplesNaitive will not load into VS2017. Have updated and downloaded everything...

Anyone else having these issues?
Cheers

**Comment by daneuber** [comment]
Hi @mrbrennonwilliams - have you checked you have all the proper SDKs installed then did right click->'reload'? SamplesNative.vcxproj has different target versions than SampleGallery project. (14393 and 10586 versus 16299 and 15063).

**Comment by daneuber** [comment]
Closing due to activity. Please re-open and add more detail if you are still having this issue. Another thing you might check is that your VS installation has C++ development packages enabled (Open VS Installer app > modify your VS installation > check 'workloads'). The SamplesNative project is the only project with this dependency that SampleGallery itself depends on.
