### ISSUE TITLE
[Question] Why use ExpressionAnimation to set CompositionConditionalValue.Condition?

### ISSUE THREAD

**Issue by HppZ** [Microsoft/WindowsCompositionSamples#285]
I mean it is a condition expression, but why use animation?

**Comment by likuba** [comment]
This was introduced as an ExpressionAnimation for scenarios where you want to create custom snap points with InteractionTracker.  There's more detail in [this article](https://docs.microsoft.com/en-us/windows/uwp/composition/inertia-modifiers), but the general idea is that if you want inertia to be modified conditionally based on some values that are only accessible via expressions (such as InteractionTracker's velocity, position, or natural rest point), you can set up a condition that references these.

**Comment by HppZ** [comment]
Why use ExpressionAnimation  rather than something like a Func or a lambda expression that returns bool  to set up a condition, in my opinion an animation is to do beautiful transitions but not do condition work. I know it is introduced to create custom snap points, I just feel strange when I use an ExpressionAnimation as a condition property value.

**Comment by likuba** [comment]
Right, the general observation that in this case an ExpressionAnimation is really being used as an "Expression" is fair.  ExpressionAnimations in Composition ended up being a much more all-purpose tool than we originally expected when building them.  In this case, we specifically ended up choosing to use ExpressionAnimations so that you could reference other CompositionObjects in setting up the conditionals.  In this case, being able to reference properties of InteractionTracker that only exist in CompositionExpressionAnimations was especially relevant.

**Comment by HppZ** [comment]
Thanks 👍
